fix(bin:lsext): incorrect error reports
Signed-off-by: Ar Rakin <rakinar2@onesoftnet.eu.org>

diff --git a/bin/lsext b/bin/lsext
--- a/bin/lsext
+++ b/bin/lsext
@@ -55,8 +55,13 @@ while [ "$#" -gt 0 ]; do
             echo "  -h, --help      Show this help message"
             exit 0
             ;;
-        *)
+        -*)
             echo "$me: invalid option: $1" >&2
+            exit 1
+            ;;
+
+        *)
+            echo "$me: invalid argument: $1" >&2
             exit 1
             ;;
     esac
@@ -110,8 +115,7 @@ list_extensions() {
     fi
     
     magic="$(head -c 16 /dev/urandom | base64 | tr -d '\n' | cut -c 1-8)"
-
-    response="$(echo $magic'{"type":"ListExtensions"}'$magic | nc -U "$socket_file")"
+    response="$(echo "$magic"'{"type":"ListExtensions"}'"$magic" | nc -U "$socket_file")"
 
     if [ $? -ne 0 ]; then
         echo "$me: unable to connect to socket: $socket_file" >&2
@@ -128,23 +132,33 @@ list_extensions() {
         exit 1
     fi
 
-    if [ "$(echo "$response" | jq -r .type)" != "ListExtensions" ]; then
+    if [ "$(echo "$response" | jq -r .type)" = "IPCError" ]; then
+        echo "$me: error: $(echo "$response" | jq -r .message)" >&2
+        exit 1
+    fi
+
+    if [ "$(echo "$response" | jq -r .type)" != "ExtensionList" ]; then
         echo "$me: invalid type in response from socket: $socket_file" >&2
         exit 1
     fi
 
-    printf "\033[1m%-20s %-10s %-10s %-20s %s\033[0m\n" "Name" "Version" "Author" "Loaded At" "Description"
+    printf "\033[1m%-30s %-20s %-10s %-10s %-20s %s\033[0m\n" "ID" "Name" "Version" "Author" "Loaded At" "Description"
 
     for extension in $(echo "$response" | jq -r '.extensions[] | @base64'); do
         _jq() {
             echo "${extension}" | base64 --decode | jq -r "${1}"
         }
 
+        id="$(_jq '.id')"
         name="$(_jq '.name')"
         version="$(_jq '.version')"
         author="$(_jq '.author')"
         loaded_at="$(_jq '.loadedAt')"
         description="$(_jq '.description')"
+
+        if [ "$id" = "null" ]; then
+            id="N/A"
+        fi
 
         if [ "$name" = "null" ]; then
             name="N/A"
@@ -169,6 +183,8 @@ list_extensions() {
             description="N/A"
         fi
 
-        printf "%-20s %-10s %-10s %-20s %s\n" "$name" "$version" "$author" "$loaded_at" "$description"
+        printf "%-30s %-20s %-10s %-10s %-20s %s\n" "$id" "$name" "$version" "$author" "$loaded_at" "$description"
     done
 }
+
+list_extensions
