build: improvements

diff --git a/blazew b/blazew
--- a/blazew
+++ b/blazew
@@ -3,6 +3,7 @@
 VERSION="1.0.0-alpha.1"
 
 argv_0=$0
+projectdir=$(dirname $0)
 
 startup() {
     echo -e "\033[1;34mBlazeBuild Wrapper version $VERSION\033[0m\n"
@@ -23,6 +24,8 @@ help() {
     echo "Tasks:"
     echo "  Any arguments or task names that should"
     echo "  be passed to BlazeBuild."
+    echo "  Run \`$argv_0 tasks' to see a list of"
+    echo "  available tasks."
     exit 0
 }
 
@@ -41,40 +44,62 @@ for arg in "$@"; do
     fi
 done
 
-if [ ! -d "build_src/node_modules" ] || [ ! -d "node_modules/blazebuild" ]; then
+if [ ! -d "$projectdir/build_src/node_modules" ] || [ ! -d "$projectdir/node_modules/blazebuild" ]; then
     setup=1
 fi
 
 has_bun=$(command -v bun)
 cmd="npm"
+file="$projectdir/build_src/build/index.js"
 
 if [ ! -z "$has_bun" ]; then
     cmd="bun"
+    file="$projectdir/build_src/src/index.ts"
+fi
+
+blaze_cmd() {
+    if [ -z "$has_bun" ]; then
+        node $file $@
+    else
+        bun $file $@
+    fi
+}
+
+if [ ! -e "$projectdir/.blaze/build.d.ts" ]; then
+    print 34 "info   " "Creating $projectdir/.blaze/build.d.ts..."
+    mkdir -p "$projectdir/.blaze"
+    cp "$projectdir/build_src/templates/build.d.ts" "$projectdir/.blaze/build.d.ts"
+
+    if [ $? -ne 0 ]; then
+        print "1;31" "error  " "Failed to create build.d.ts."
+        exit 1
+    fi
 fi
 
 if [ $setup -eq 1 ]; then
     startup
+    print 34 "info   " "Project directory: $projectdir"
     print 34 "info   " "Setting up BlazeBuild..."
-    rm -rf build_src/node_modules
-    cd build_src
+    rm -rf "$projectdir/build_src/node_modules"
+    pushd "$projectdir/build_src"
 
     print 34 "info   " "Installing dependencies for BlazeBuild..."
     print 36 "command" "$cmd install"
     command $cmd install
-    cd ..
+    popd
 
     print 34 "info   " "Finishing up..."
-    mkdir -p node_modules
+    mkdir -p "$projectdir/node_modules"
 
-    if [ ! -e node_modules/blazebuild ]; then
-        ln -s $(pwd)/build_src node_modules/blazebuild
+    if [ ! -e "$projectdir/node_modules/blazebuild" ]; then
+        ln -s "$projectdir/build_src" "$projectdir/node_modules/blazebuild"
     fi
 
     if [ -z "$has_bun" ]; then
         print 34 "info   " "Building BlazeBuild (for node)..."
-        cd build_src
+        pushd "$projectdir/build_src"
         npx tsc
-        cd ..
+        popd
     fi
 
     print "1;32" "success" "Setup completed."
@@ -84,4 +109,4 @@ if [ $argsetup -eq 1 ]; then
     exit 0
 fi
 
-bun build_src/src/index.ts $@
+blaze_cmd $@
