feat(blazebuild): improved blaze wrapper

diff --git a/blazew b/blazew
--- a/blazew
+++ b/blazew
@@ -24,7 +24,7 @@ mkdir -p "$tmp_dir"
 mkdir -p "$nvm_home"
 
 getprop() {
-   value=$(cat "$projectdir/blaze/blaze_wrapper.properties" | grep "$1" | cut -d'=' -f2)
+   value=$(cat "$projectdir/blaze/wrapper/blaze_wrapper.properties" | grep "$1" | cut -d'=' -f2)
    echo $value
 }
 
@@ -236,11 +236,6 @@ for arg in "$@"; do
     if [ "$arg" == "--setup" ]; then
         setup=1
         argsetup=1
-    elif [ "$arg" == "--help" ]; then
-        help
-    elif [ "$arg" == "--version" ]; then
-        startup
-        exit 0
     fi
 done
 
@@ -257,7 +252,6 @@ if [ "$node" == "node" ]; then
     cmd="npm"
 fi
 
-echo $bun
 file="$blaze_srcpath/build/index.js"
 if [ ! -z "$has_bun" ] || [ $setup_done -eq 1 ] || [ -x "$bun" ]; then
     cmd=$bun
@@ -268,11 +262,14 @@ fi
 blaze_cmd() {
     node_path=$(dirname "$node")
     final_path=$(readlink -f $node_path)
+    wrapper=$(readlink -f "$projectdir/blaze/wrapper/blaze_wrapper.mjs")
 
     if [ -z "$has_bun" ]; then
-        export PATH="$final_path":$PATH:"$final_path" && bash -c "$node $file $@"
+        print "1;31" "error  " "Bun not found. Please install Bun to use BlazeBuild."
+        exit 1
+        export PATH="$final_path":$PATH:"$final_path" && bash -c "exec -a \"$argv_0\" $node $wrapper $file -- $*"
     else
-        export PATH="$final_path":$PATH:"$final_path" && bash -c "$cmd $file $*"
+        export PATH="$final_path":$PATH:"$final_path" && bash -c "exec -a \"$argv_0\" $cmd $wrapper $file -- $*"
     fi
 }
 
@@ -303,7 +300,7 @@ if [ $setup -eq 1 ]; then
     mkdir -p "$projectdir/node_modules"
 
     if [ -L "$projectdir/node_modules/blazebuild" ] || [ -d "$projectdir/node_modules/blazebuild" ]; then
-        rm "$projectdir/node_modules/blazebuild" || exit 1
+        rm -rf "$projectdir/node_modules/blazebuild" || exit 1
     fi
 
     ln -s "$(readlink -f "$blaze_srcpath")" "$projectdir/node_modules/blazebuild" || exit 1
