build(linux:pkg): only use nodejs by default
Signed-off-by: Ar Rakin <rakinar2@onesoftnet.eu.org>

diff --git a/packages/common/bin/sudobot b/packages/common/bin/sudobot
--- a/packages/common/bin/sudobot
+++ b/packages/common/bin/sudobot
@@ -2,10 +2,16 @@
 
 cd /usr/share/sudobot || exit 1
 
-bun="$(pwd)/.blazebuild/bun/bin/bun"
-
-if [ ! -f "$bun" ]; then
-    bun=bun
+if ! command -v node >/dev/null 2>&1; then
+  echo "$0: error: Node.js is not installed. Please install Node.js to run SudoBot." >&2
+  exit 1
 fi
 
-exec "$bun" -- start:bun
+current_user=$(id -u -n)
+
+if [ "$current_user" != "sudobot" ]; then
+  echo "$0: warning: You are not running this as the 'sudobot' user. This may cause permission issues." >&2
+  echo "$0: It is recommended to run this script as the 'sudobot' user." >&2
+fi
+
+exec node --env-file-if-exists=/etc/sudobot/env -- build/out/main/typescript/main.js "$@"
