ci: update workflows

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,6 +29,9 @@ jobs:
     - name: "Install Dev Dependencies"
       run: npm install --dev
 
+    - name: "ESLint"
+      run: npm run lint || echo "ESLint Failed"
+
     - name: "Build"
       run: npm run build --if-present
 
