ci: update build workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -3,37 +3,50 @@
 
 name: Build
 
-on: [ push, pull_request ]
+on: [push, pull_request]
 
 jobs:
-  build:
+    build:
+        runs-on: ubuntu-latest
 
-    runs-on: ubuntu-latest
+        strategy:
+            matrix:
+                node-version: [18.x, 20.x]
+                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
-    strategy:
-      matrix:
-        node-version: [18.x, 20.x]
-        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
+        steps:
+            - uses: actions/checkout@v3
 
-    steps:
-    - uses: actions/checkout@v3
-    
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v3
-      with:
-        node-version: ${{ matrix.node-version }}
-    
-    - name: "Install Dependencies"
-      run: npm install
+            - name: Use Node.js ${{ matrix.node-version }}
+              uses: actions/setup-node@v3
+              with:
+                  node-version: ${{ matrix.node-version }}
 
-    - name: "Install Dev Dependencies"
-      run: npm install -D
+            - name: "Install Tools"
+              run: sudo apt install build-essential libcurl4 libcurl4-gnutls-dev -y
 
-    - name: "Generate prisma client"
-      run: npx prisma generate
+            - name: "Install Native Libraries"
+              run: |
+                  git clone https://github.com/Cogmasters/concord;
+                  cd concord;
+                  make;
+                  sudo make install;
+                  cd ..;
 
-    - name: "ESLint"
-      run: npm run lint || echo "ESLint Failed"
+            - name: "Install Dependencies"
+              run: npm install
 
-    - name: "Build"
-      run: npm run build --if-present
+            - name: "Install Dev Dependencies"
+              run: npm install -D
+
+            - name: "Generate prisma client"
+              run: npx prisma generate
+
+            - name: "ESLint"
+              run: npm run lint || echo "ESLint Failed"
+
+            - name: "Build (TypeScript)"
+              run: npm run build --if-present
+
+            - name: "Build (Native)"
+              run: make
